---
- hosts: test_machine
  become: yes

  pre_tasks:
  - apt:
      name: python-docker
      update_cache: yes

  post_tasks:
  - apt:
      name: python-docker
      state: absent
      purge: yes

  roles:
  - role: '.'
    version: 3.3.1
    artifact_checksum: b3891341a9ff4c4b6b0173ac57f1d64d4752550c95eeb26d2518ac2f5ca9fbc1
    publish:
      interface: 0.0.0.0
      default_port: 9987
      filetransfer_port: 30033
      serverquery_port: 10011
      tsdns_port: 41144
    volumes:
      data: /srv/docker/teamspeak
      log: /var/log/teamspeak
