---
- hosts: test_machine
  become: yes

  pre_tasks:
  - apt:
      name: python-docker
      update_cache: yes

  post_tasks:
  - apt:
      name: python-docker
      state: absent
      purge: yes

  roles:
  - role: '.'
    version: 3.1.0
    artifact_checksum: 9f18cff600b9ce82a26ab788633cd5004bbe8c86963507efd3704c085f50a391
    publish:
      interface: 0.0.0.0
      default_port: 9987
      filetransfer_port: 30033
      serverquery_port: 10011
      tsdns_port: 41144
    volumes:
      data: /srv/docker/teamspeak
      log: /var/log/teamspeak
