---
- name: Check 'teamspeak_data_volume' parameter
  assert:
    that:
      - "teamspeak_data_volume is defined"
      - "teamspeak_data_volume | length > 0"
    fail_msg: "parameter 'teamspeak_data_volume' is missing"

- name: Check 'teamspeak_log_volume' parameter
  assert:
    that:
      - "teamspeak_log_volume is defined"
      - "teamspeak_log_volume | length > 0"
    fail_msg: "parameter 'teamspeak_log_volume' is missing"

- name: Check 'teamspeak_files_volume' parameter
  assert:
    that:
      - "teamspeak_files_volume is defined"
      - "teamspeak_files_volume | length > 0"
    fail_msg: "parameter 'teamspeak_files_volume' is missing"
