---
- name: Create data volume directory
  file:
    path: "{{ volumes.data }}"
    state: directory
    owner: "{{ user_uid }}"
    group: "{{ user_uid }}"
    mode: 0750

- name: Create log volume directory
  file:
    path: "{{ volumes.log }}"
    state: directory
    owner: "{{ user_uid }}"
    group: "{{ user_uid }}"
    mode: 0750

- name: Create files volume directory
  file:
    path: "{{ volumes.files }}"
    state: directory
    owner: "{{ user_uid }}"
    group: "{{ user_uid }}"
    mode: 0750
