---
- name: Create data volume directory
  file:
    path: "{{ teamspeak_data_volume }}"
    state: directory
    owner: "{{ teamspeak_user_uid }}"
    group: "{{ teamspeak_user_uid }}"
    mode: 0750

- name: Create log volume directory
  file:
    path: "{{ teamspeak_log_volume }}"
    state: directory
    owner: "{{ teamspeak_user_uid }}"
    group: "{{ teamspeak_user_uid }}"
    mode: 0750

- name: Create files volume directory
  file:
    path: "{{ teamspeak_files_volume }}"
    state: directory
    owner: "{{ teamspeak_user_uid }}"
    group: "{{ teamspeak_user_uid }}"
    mode: 0750
