---
- name: pull docker image
  docker_image:
    name: "{{docker_image.name}}:{{docker_image.tag}}"
    source: pull
  register: dockerimage

- name: create volume directories
  file:
    path: "{{item.value}}"
    state: directory
    owner: "{{user_uid}}"
    group: "{{user_uid}}"
    mode: '0754'
  when: item.value is defined and item.value != ''
  with_dict: "{{docker_container.volumes}}"

- name: Create systemd unit file
  template:
    src: systemd.unitfile.j2
    dest: "/etc/systemd/system/{{service_name}}.service"
    owner: root
    group: root
    mode: '0640'
  register: systemd_unitfile

- name: Reload systemd
  command: systemctl daemon-reload
  when: systemd_unitfile.changed

- name: Restart service
  service:
    name: "{{service_name}}"
    state: restarted
    enabled: yes
  when: dockerimage.changed or systemd_unitfile.changed

- name: Start service (if not started already)
  service:
    name: "{{service_name}}"
    state: started
