---
- include: check-parameters.yml

- name: pull docker image
  docker_image:
    name: "{{ docker_image.name }}:{{ docker_image.tag }}"
    source: pull
    state: present
  notify: Restart teamspeak service

- include: create-volumes.yml

- name: Create systemd unit file
  template:
    src: systemd.unitfile.j2
    dest: "/etc/systemd/system/{{ service_name }}.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload systemd
    - Restart teamspeak service

- name: Enable service
  service:
    name: "{{ service_name }}"
    enabled: true
  register: teamspeak_service
  changed_when: teamspeak_service.status.SubState != 'running'
  notify: Start teamspeak service
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )

- name: Start systemd-managed docker containers
  meta: flush_handlers
