---
- include: check-parameters.yml

- name: pull docker image
  docker_image:
    name: "teamspeak:{{ teamspeak_version }}"
    source: pull
    state: present
  notify: Restart teamspeak service

- include: create-volumes.yml

- name: Create systemd unit file
  template:
    src: systemd.unitfile.j2
    dest: "/etc/systemd/system/{{ teamspeak_service_name }}.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart teamspeak service

- name: Start systemd-managed docker containers
  meta: flush_handlers

- name: Enable service (if not started)
  service:
    name: "{{ teamspeak_service_name }}"
    enabled: true
    state: started
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )
