---
- name: create dockercompose directory
  file:
    path: "{{docker_compose.workingdir}}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: template docker-compose file
  template:
    src: ./docker/docker-compose.yml.j2
    dest: "{{docker_compose.workingdir}}/{{docker_compose.filename}}"
    owner: root
    group: root
    mode: 0554
  register: dockercompose_file
