---
- name: Reload systemd
  systemd:
    daemon_reload: true
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )

- name: Start teamspeak service
  service:
    name: "{{ service_name }}"
    state: started
  register: teamspeak_start

- name: Restart teamspeak service
  service:
    name: "{{ service_name }}"
    state: restarted
  when: not (
    teamspeak_start is defined
    and teamspeak_start.changed
    )
    and not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )
