---
- name: Restart teamspeak service
  service:
    name: "{{ teamspeak_service_name }}"
    state: restarted
    daemon_reload: true
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )
