---
dependency:
  name: galaxy
  options:
    role-file: ./molecule/shared/requirements.yml

driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: ansible-teamspeak-xenial
    box: ubuntu/xenial64
  - name: ansible-teamspeak-bionic
    box: ubuntu/bionic64
  - name: ansible-teamspeak-focal
    box: ubuntu/focal64
  - name: ansible-teamspeak-stretch
    box: debian/stretch64
  - name: ansible-teamspeak-buster
    box: debian/buster64

provisioner:
  name: ansible
  playbooks:
    prepare: ../shared/prepare.yml
  inventory:
    host_vars:
      ansible-teamspeak-stretch:
        ansible_python_interpreter: /usr/bin/python3
      ansible-teamspeak-buster:
        ansible_python_interpreter: /usr/bin/python3

verifier:
  name: ansible
