---
dependency:
  name: galaxy
  options:
    role-file: ./molecule/shared/requirements.yml

lint: |
  set -e
  yamllint . --strict
  ansible-lint

driver:
  name: docker

platforms:
  - name: ansible-teamspeak-ubuntu
    image: docker.io/borisskert/python3:focal
    pull: true
    pre_build_image: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    groups:
      - docker
  - name: ansible-teamspeak-debian
    image: docker.io/borisskert/python3:buster
    pull: true
    pre_build_image: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    groups:
      - docker

provisioner:
  name: ansible
  playbooks:
    prepare: ../shared/prepare.yml
  inventory:
    group_vars:
      docker:
        molecule_docker_environment: true
        no_log: false
    host_vars:
      ansible-teamspeak-debian:
        ansible_python_interpreter: /usr/bin/python3

verifier:
  name: ansible
