---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: ansible-teamspeak
      teamspeak_version: '3.12'
      teamspeak_data_volume: /srv/teamspeak/data
      teamspeak_log_volume: /var/log/teamspeak
      teamspeak_files_volume: /srv/teamspeak/files
      teamspeak_interface: 0.0.0.0
      teamspeak_port: 9987
      teamspeak_filestransfer_port: 30033
      teamspeak_serverquery_port: 10011
      teamspeak_accept_license: true
